export const restaurant = {
  name: "Rangoli Sweets & Chaats",
  description: "Authentic North Indian Mithai & Street Food Since 1987",
  logo: "/images/peacocklogo.webp",
  heroImage: "/images/sweets.webp",
};

export const categories = [
  { id: "chaat", name: "Chaat Corner" },
  { id: "mithai", name: "Premium Mithai" },
  { id: "snacks", name: "Hot Snacks" },
  { id: "beverages", name: "Beverages" },
];

export const items = [

  // ─── CHAAT ───────────────────────────────────────────────────────────────
  {
    id: "c1",
    categoryId: "chaat",
    name: "Pani Puri (6 Pcs)",
    description: "Crispy hollow puris burst-filled with tangy mint water, sweet tamarind chutney, and spiced potato-chickpea filling. Our house recipe, unchanged since 1987.",
    price: 60,
    image: "https://images.unsplash.com/photo-1586357507341-3fbe59f2a5d9?q=80&w=580&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["Vegan", "Spicy", "Bestseller"],
  },
  {
    id: "c2",
    categoryId: "chaat",
    name: "Sev Puri",
    description: "Flat crispy puris layered with diced potatoes, onion, tomato, fresh chutneys, and a generous shower of crunchy sev. Light, tangy, and utterly addictive.",
    price: 70,
    image: "https://images.pexels.com/photos/34270741/pexels-photo-34270741.jpeg",
    tags: ["Vegan", "Crunchy"],
  },
  {
    id: "c3",
    categoryId: "chaat",
    name: "Dahi Puri (6 Pcs)",
    description: "Hollow puris filled with potato mash, topped with thick chilled dahi, tamarind-date chutney, green chutney, and fine sev. Cool, creamy perfection.",
    price: 80,
    image: "https://images.pexels.com/photos/32894826/pexels-photo-32894826.jpeg",
    tags: ["Vegetarian", "Refreshing"],
  },
  {
    id: "c4",
    categoryId: "chaat",
    name: "Aloo Tikki Chaat",
    description: "Two golden, crisp-fried potato patties served on a bed of chole, drizzled with yogurt, tamarind chutney, green chutney, and topped with sev.",
    price: 90,
    image: "https://images.unsplash.com/photo-1559561723-bcb9e0db1d66?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["Vegetarian", "Bestseller"],
  },
  {
    id: "c5",
    categoryId: "chaat",
    name: "Papdi Chaat",
    description: "Crispy flour discs piled with boiled chickpeas, potatoes, chilled dahi, two chutneys, and a dusting of chaat masala. A true North Indian classic.",
    price: 85,
    image: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?q=80&w=776&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["Vegetarian"],
  },
  {
    id: "c6",
    categoryId: "chaat",
    name: "Raj Kachori",
    description: "A giant, crispy kachori bowl filled with sprouts, aloo, boondi, dahi, and all four chutneys — the king of chaats. Served fresh and piled high.",
    price: 130,
    image: "https://images.pexels.com/photos/33290173/pexels-photo-33290173.jpeg",
    tags: ["Vegetarian", "Signature", "Filling"],
  },
  {
    id: "c7",
    categoryId: "chaat",
    name: "Dahi Bhalla",
    description: "Soft, pillowy urad dal vadas soaked until they melt, topped with cold dahi, sweet tamarind, tangy green chutney, and red chilli powder.",
    price: 90,
    image: "https://images.pexels.com/photos/16171913/pexels-photo-16171913.jpeg",
    tags: ["Vegetarian", "Soft"],
  },
  {
    id: "c8",
    categoryId: "chaat",
    name: "Bhel Puri",
    description: "A tangy toss of puffed rice, thin sev, onion, tomato, raw mango, and coriander — freshly mixed with our signature chutneys to order.",
    price: 70,
    image: "https://images.pexels.com/photos/35213277/pexels-photo-35213277.jpeg",
    tags: ["Vegan", "Light"],
  },

  // ─── MITHAI ──────────────────────────────────────────────────────────────
  {
    id: "m1",
    categoryId: "mithai",
    name: "Kaju Katli (250g)",
    description: "Diamond-shaped fudge crafted from premium whole cashews, slow-cooked with sugar syrup and draped in edible silver varq. A gift-worthy classic.",
    price: 320,
    image: "https://images.unsplash.com/photo-1699708263762-00ca477760bd?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["Vegetarian", "Gift Pack", "Contains Nuts"],
  },
  {
    id: "m2",
    categoryId: "mithai",
    name: "Gulab Jamun (2 Pcs)",
    description: "Warm, cloud-soft milk-solid dumplings, fried to a mahogany brown and soaked overnight in cardamom and saffron sugar syrup. Served warm.",
    price: 60,
    image: "https://images.pexels.com/photos/15014919/pexels-photo-15014919.jpeg",
    tags: ["Vegetarian", "Bestseller", "Warm"],
  },
  {
    id: "m3",
    categoryId: "mithai",
    name: "Rasmalai (2 Pcs)",
    description: "Delicate chenna discs simmered in rich, reduced saffron milk, garnished with crushed pistachios. Chilled and luxurious.",
    price: 100,
    image: "https://images.pexels.com/photos/8788869/pexels-photo-8788869.jpeg",
    tags: ["Vegetarian", "Chilled", "Premium"],
  },
  {
    id: "m4",
    categoryId: "mithai",
    name: "Gajar Ka Halwa (Bowl)",
    description: "Slow-cooked red Desi carrots stirred for hours with full-fat milk, desi ghee, and sugar, then topped with a handful of roasted dry fruits.",
    price: 110,
    image: "https://images.pexels.com/photos/35532835/pexels-photo-35532835.jpeg",
    tags: ["Vegetarian", "Seasonal", "Warm"],
  },
  {
    id: "m5",
    categoryId: "mithai",
    name: "Jalebi (250g)",
    description: "Freshly piped batter spirals, fried in desi ghee until glass-crisp, then dipped in warm sugar syrup. Made to order every hour.",
    price: 90,
    image: "https://images.pexels.com/photos/36021117/pexels-photo-36021117.jpeg",
    tags: ["Vegetarian", "Crispy", "Fresh"],
  },
  {
    id: "m6",
    categoryId: "mithai",
    name: "Motichoor Ladoo (250g)",
    description: "Tiny, bead-like boondi droplets fried in ghee and bound with fragrant sugar syrup and melon seeds into perfectly round, moist ladoos.",
    price: 200,
    image: "https://images.pexels.com/photos/19151502/pexels-photo-19151502.jpeg",
    tags: ["Vegetarian", "Gift Pack"],
  },

  // ─── SNACKS ──────────────────────────────────────────────────────────────
  {
    id: "s1",
    categoryId: "snacks",
    name: "Samosa (2 Pcs)",
    description: "Thick, flaky pastry cones stuffed with a mildly spiced filling of potatoes, green peas, coriander, and garam masala. Served with mint & tamarind chutneys.",
    price: 40,
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["Vegan", "Crispy", "Bestseller"],
  },
  {
    id: "s2",
    categoryId: "snacks",
    name: "Pyaaz Kachori (2 Pcs)",
    description: "Deep-fried, puffed pastry stuffed with a punchy filling of caramelised onions, fennel, and spices. A Rajasthani gem — crispy outside, flavour bomb inside.",
    price: 60,
    image: "https://images.pexels.com/photos/30846048/pexels-photo-30846048.jpeg",
    tags: ["Vegetarian", "Rajasthani"],
  },
  {
    id: "s3",
    categoryId: "snacks",
    name: "Paneer Pakoda (6 Pcs)",
    description: "Thick cubes of fresh cottage cheese marinated in spices, coated in a besan batter seasoned with ajwain, and fried until deeply golden.",
    price: 130,
    image: "https://images.pexels.com/photos/37107128/pexels-photo-37107128.jpeg",
    tags: ["Vegetarian", "Protein Rich"],
  },
  {
    id: "s4",
    categoryId: "snacks",
    name: "Mix Pakoda Platter",
    description: "A generous sharing platter of 12 assorted pakodas — onion, spinach, paneer, and potato — served with two chutneys. Perfect for groups.",
    price: 180,
    image: "https://images.pexels.com/photos/9738980/pexels-photo-9738980.jpeg",
    tags: ["Vegetarian", "Sharing", "Popular"],
  },

  // ─── BEVERAGES ───────────────────────────────────────────────────────────
  {
    id: "b1",
    categoryId: "beverages",
    name: "Mango Lassi",
    description: "Thick, cold yogurt whipped with ripe Alphonso mango pulp, a pinch of cardamom, and a drizzle of saffron milk. Rich, creamy, and deeply satisfying.",
    price: 90,
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["Vegetarian", "Chilled", "Bestseller"],
  },
  {
    id: "b2",
    categoryId: "beverages",
    name: "Rose Lassi",
    description: "Chilled full-fat dahi blended with pure rose syrup, topped with fresh cream and crushed pistachios. Sweet, floral, and utterly refreshing.",
    price: 80,
    image: "https://images.pexels.com/photos/8917283/pexels-photo-8917283.jpeg",
    tags: ["Vegetarian", "Chilled", "Sweet"],
  },
  {
    id: "b3",
    categoryId: "beverages",
    name: "Masala Chai",
    description: "Strong Assam tea simmered with fresh ginger, cardamom, cloves, and cinnamon. Served hot in a cutting glass with just the right amount of milk.",
    price: 30,
    image: "https://images.unsplash.com/photo-1625033405953-f20401c7d848?q=80&w=387&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    tags: ["Vegetarian", "Hot", "Classic"],
  },
  {
    id: "b4",
    categoryId: "beverages",
    name: "Shikanji",
    description: "Old Delhi–style fresh lemonade with black salt, roasted cumin, and mint. Our thirst-quenching answer to the Indian summer.",
    price: 50,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=800&auto=format&fit=crop",
    tags: ["Vegan", "Chilled", "Refreshing"],
  },
];